/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractVcardValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.compil.dslvisitcard.dvc.vcard.VcardPackage.eINSTANCE);
		return result;
	}
}
