/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VcardRuntimeModule extends AbstractVcardRuntimeModule {
}
