/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVcardScopeProvider extends DelegatingScopeProvider {
}
