/**
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.vcard;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Card</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.compil.dslvisitcard.dvc.vcard.Card#getName <em>Name</em>}</li>
 *   <li>{@link org.compil.dslvisitcard.dvc.vcard.Card#getTitle <em>Title</em>}</li>
 *   <li>{@link org.compil.dslvisitcard.dvc.vcard.Card#getCompany <em>Company</em>}</li>
 *   <li>{@link org.compil.dslvisitcard.dvc.vcard.Card#getEmail <em>Email</em>}</li>
 *   <li>{@link org.compil.dslvisitcard.dvc.vcard.Card#getPhone <em>Phone</em>}</li>
 * </ul>
 *
 * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getCard()
 * @model
 * @generated
 */
public interface Card extends EObject
{
  String email = null;

/**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getCard_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.compil.dslvisitcard.dvc.vcard.Card#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getCard_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.compil.dslvisitcard.dvc.vcard.Card#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Company</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company</em>' attribute.
   * @see #setCompany(String)
   * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getCard_Company()
   * @model
   * @generated
   */
  String getCompany();

  /**
   * Sets the value of the '{@link org.compil.dslvisitcard.dvc.vcard.Card#getCompany <em>Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Company</em>' attribute.
   * @see #getCompany()
   * @generated
   */
  void setCompany(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getCard_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.compil.dslvisitcard.dvc.vcard.Card#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Phone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phone</em>' attribute.
   * @see #setPhone(String)
   * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getCard_Phone()
   * @model
   * @generated
   */
  String getPhone();

  /**
   * Sets the value of the '{@link org.compil.dslvisitcard.dvc.vcard.Card#getPhone <em>Phone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phone</em>' attribute.
   * @see #getPhone()
   * @generated
   */
  void setPhone(String value);

} // Card
