/**
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.vcard;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.compil.dslvisitcard.dvc.vcard.Model#getCards <em>Cards</em>}</li>
 * </ul>
 *
 * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Cards</b></em>' containment reference list.
   * The list contents are of type {@link org.compil.dslvisitcard.dvc.vcard.Card}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cards</em>' containment reference list.
   * @see org.compil.dslvisitcard.dvc.vcard.VcardPackage#getModel_Cards()
   * @model containment="true"
   * @generated
   */
  EList<Card> getCards();

} // Model
