/**
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.vcard;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.compil.dslvisitcard.dvc.vcard.VcardFactory
 * @model kind="package"
 * @generated
 */
public interface VcardPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vcard";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.compil.org/dslvisitcard/dvc/Vcard";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vcard";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VcardPackage eINSTANCE = org.compil.dslvisitcard.dvc.vcard.impl.VcardPackageImpl.init();

  /**
   * The meta object id for the '{@link org.compil.dslvisitcard.dvc.vcard.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.compil.dslvisitcard.dvc.vcard.impl.ModelImpl
   * @see org.compil.dslvisitcard.dvc.vcard.impl.VcardPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Cards</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CARDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.compil.dslvisitcard.dvc.vcard.impl.CardImpl <em>Card</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.compil.dslvisitcard.dvc.vcard.impl.CardImpl
   * @see org.compil.dslvisitcard.dvc.vcard.impl.VcardPackageImpl#getCard()
   * @generated
   */
  int CARD = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__TITLE = 1;

  /**
   * The feature id for the '<em><b>Company</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__COMPANY = 2;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__EMAIL = 3;

  /**
   * The feature id for the '<em><b>Phone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__PHONE = 4;

  /**
   * The number of structural features of the '<em>Card</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.compil.dslvisitcard.dvc.vcard.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.compil.dslvisitcard.dvc.vcard.Model#getCards <em>Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cards</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Model#getCards()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Cards();

  /**
   * Returns the meta object for class '{@link org.compil.dslvisitcard.dvc.vcard.Card <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Card
   * @generated
   */
  EClass getCard();

  /**
   * Returns the meta object for the attribute '{@link org.compil.dslvisitcard.dvc.vcard.Card#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Card#getName()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Name();

  /**
   * Returns the meta object for the attribute '{@link org.compil.dslvisitcard.dvc.vcard.Card#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Card#getTitle()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Title();

  /**
   * Returns the meta object for the attribute '{@link org.compil.dslvisitcard.dvc.vcard.Card#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Company</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Card#getCompany()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Company();

  /**
   * Returns the meta object for the attribute '{@link org.compil.dslvisitcard.dvc.vcard.Card#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Card#getEmail()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Email();

  /**
   * Returns the meta object for the attribute '{@link org.compil.dslvisitcard.dvc.vcard.Card#getPhone <em>Phone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phone</em>'.
   * @see org.compil.dslvisitcard.dvc.vcard.Card#getPhone()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Phone();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VcardFactory getVcardFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.compil.dslvisitcard.dvc.vcard.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.compil.dslvisitcard.dvc.vcard.impl.ModelImpl
     * @see org.compil.dslvisitcard.dvc.vcard.impl.VcardPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Cards</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CARDS = eINSTANCE.getModel_Cards();

    /**
     * The meta object literal for the '{@link org.compil.dslvisitcard.dvc.vcard.impl.CardImpl <em>Card</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.compil.dslvisitcard.dvc.vcard.impl.CardImpl
     * @see org.compil.dslvisitcard.dvc.vcard.impl.VcardPackageImpl#getCard()
     * @generated
     */
    EClass CARD = eINSTANCE.getCard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__NAME = eINSTANCE.getCard_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__TITLE = eINSTANCE.getCard_Title();

    /**
     * The meta object literal for the '<em><b>Company</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__COMPANY = eINSTANCE.getCard_Company();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__EMAIL = eINSTANCE.getCard_Email();

    /**
     * The meta object literal for the '<em><b>Phone</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__PHONE = eINSTANCE.getCard_Phone();

  }

} //VcardPackage
