/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VcardAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/compil/dslvisitcard/dvc/parser/antlr/internal/InternalVcard.tokens");
	}
}
