/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.compil.dslvisitcard.dvc.ide.contentassist.antlr.internal.InternalVcardParser;
import org.compil.dslvisitcard.dvc.services.VcardGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class VcardParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(VcardGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, VcardGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCardAccess().getGroup(), "rule__Card__Group__0");
			builder.put(grammarAccess.getModelAccess().getCardsAssignment(), "rule__Model__CardsAssignment");
			builder.put(grammarAccess.getCardAccess().getNameAssignment_3(), "rule__Card__NameAssignment_3");
			builder.put(grammarAccess.getCardAccess().getTitleAssignment_5(), "rule__Card__TitleAssignment_5");
			builder.put(grammarAccess.getCardAccess().getCompanyAssignment_7(), "rule__Card__CompanyAssignment_7");
			builder.put(grammarAccess.getCardAccess().getEmailAssignment_9(), "rule__Card__EmailAssignment_9");
			builder.put(grammarAccess.getCardAccess().getPhoneAssignment_11(), "rule__Card__PhoneAssignment_11");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private VcardGrammarAccess grammarAccess;

	@Override
	protected InternalVcardParser createParser() {
		InternalVcardParser result = new InternalVcardParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public VcardGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VcardGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
