/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VcardUiModule extends AbstractVcardUiModule {

	public VcardUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
