/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.ui.tests;

import com.google.inject.Injector;
import org.compil.dslvisitcard.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class VcardUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.compil.dslvisitcard.dvc.Vcard");
	}

}
