/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.validation;

import org.compil.dslvisitcard.dvc.vcard.Card;
import org.compil.dslvisitcard.dvc.vcard.VcardPackage;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class VcardValidator extends AbstractVcardValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					VcardPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}

	
	@Check
    public void checkEmailFormat(Card card) {
        if (!Card.email.matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}")) {
            warning("Invalid email format", VcardPackage.Literals.CARD__EMAIL) ;
        }
    }
}
