/*
 * generated by Xtext 2.30.0
 */
package org.compil.dslvisitcard.dvc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.compil.dslvisitcard.dvc.VcardRuntimeModule;
import org.compil.dslvisitcard.dvc.VcardStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VcardIdeSetup extends VcardStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VcardRuntimeModule(), new VcardIdeModule()));
	}
	
}
